Fix missing-prototypes
xfpm-power-common.c:100:1: error: no previous prototype for 'xfpm_battery_get_icon_index' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>