Fix va_args usage in get_device_icon_name
xfpm-power-common.c: In function 'get_device_icon_name':
xfpm-power-common.c:257:52: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
  257 |     icon_name = g_strdup_printf (is_panel ? "%s-%s", XFPM_AC_ADAPTER_ICON, "-symbolic" : "%s", XFPM_AC_ADAPTER_ICON);
      |                                                    ^
xfpm-power-common.c:257:74: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
  257 |     icon_name = g_strdup_printf (is_panel ? "%s-%s", XFPM_AC_ADAPTER_ICON, "-symbolic" : "%s", XFPM_AC_ADAPTER_ICON);
      |                                                                          ^
xfpm-power-common.c:269:52: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
  269 |     icon_name = g_strdup_printf (is_panel ? "%s-%s", XFPM_AC_ADAPTER_ICON, "-symbolic" : "%s", XFPM_AC_ADAPTER_ICON);
      |                                                    ^
xfpm-power-common.c:269:74: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
  269 |     icon_name = g_strdup_printf (is_panel ? "%s-%s", XFPM_AC_ADAPTER_ICON, "-symbolic" : "%s", XFPM_AC_ADAPTER_ICON);

Fixes commit b6d6bf8b55ecce11d0c00b1267ce03fe9b9df44e
Fixes issue #103

Signed-off-by: Olaf Hering <olaf@aepfle.de>